[package]
name = "bip347-enforcer"
version = "0.1.0"
edition = "2021"

[build-dependencies]
cc = "1.0.101"

[dependencies]
anyhow = "1.0.102"
bitcoin = { version = "0.32.2", features = ["rand", "serde"] }
clap = { version = "4.5.7", features = ["derive"] }
futures = "0.3.30"
integer-sqrt = "0.1.5"
jsonrpsee = { version = "0.26.0", features = ["server"] }
libc = "0.2.155"
rand = "0.8.5"
serde = "1.0.204"
serde_json = "1.0.120"
serde_path_to_error = "0.1.16"
serde_tuple = "0.5.0"
thiserror = "1.0.63"
tokio = { version = "1.38.0", features = ["macros", "rt-multi-thread"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"

[dependencies.bitcoin-jsonrpsee]
git = "https://github.com/LayerTwo-Labs/bitcoin-jsonrpsee.git"
rev = "db1fdfd5ecddfc7855cd872546b47429cb29a0bf"
features = ["tracing"]

[dependencies.cusf-enforcer-mempool]
git = "https://github.com/LayerTwo-Labs/cusf-enforcer-mempool"
rev = "4fa57ffc01197de508a301ea9e191517c04f235f"

[dev-dependencies]
bitcoin = { version = "0.32.2", features = ["bitcoinconsensus"] }

[[bin]]
name = "gen-demo-tx"
path = "src/gen_tx.rs"
